language: go
sudo: false
services:
  - docker
matrix:
  include:
  - os: osx
    go: 1.11.x
    env:
      - TARGET=darwin
      - ARCH=amd64
  - os: linux
    go: 1.11.x
    env:
      - TARGET=linux
      - ARCH=amd64
notifications:
  email: false
install:
- dep ensure
script:
- make build