language: go
sudo: false
services:
  - docker
matrix:
  include:
  - os: linux
    go: 1.11.x
    env:
      - TARGET=linux
      - ARCH=amd64
notifications:
  email: false
before_install:
- pip install --user awscli
- curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
install:
- dep ensure
script:
- make build